# eureka client configure
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  # application name
  application:
    name: movie-service-user
  # database
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sc_movie?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  # date format
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

# actuator
management:
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: peer1
server:
  port: 8701

---
spring:
  profiles: peer2
server:
  port: 8702